pipeline {
    agent any

    stages {
        stage('Checkout and Build') {
            steps {
                script {
                    // Create a temporary shell script file
                    writeFile file: 'build_and_publish.sh', text: '''#!/bin/bash
                    DOTNET_VERSION="6.0.0"
                    REPO_URL="https://github.com/your/repo.git"
                    PROJECT_DIR="your-project-dir"
                    git clone $REPO_URL
                    cd $PROJECT_DIR
                    if ! command -v dotnet &> /dev/null
                    then
                        wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
                        chmod +x dotnet-install.sh
                        ./dotnet-install.sh --version $DOTNET_VERSION
                        export PATH=$HOME/.dotnet:$PATH
                    fi
                    dotnet restore
                    dotnet build --configuration Release
                    dotnet test --configuration Release
                    dotnet publish --configuration Release --output ./publish
                    tar -czvf publish.tar.gz -C ./publish .
                    '''

                    // Run the shell script
                    sh 'chmod +x build_and_publish.sh'
                    sh './build_and_publish.sh'
                }
            }
        }
        stage('Archive Artifacts') {
            steps {
                // Archive the artifacts generated by the build
                archiveArtifacts artifacts: 'your-project-dir/publish.tar.gz', allowEmptyArchive: false
            }
        }
    }
    post {
        always {
            // Clean up workspace
            cleanWs()
        }
    }
}


